[package]
name = "epirust"
version = "0.0.1"
license = "MIT or Apache-2.0"
description = "Crate for epidemiological agent-based simulations."
authors = ["Jayanta K Kshirsagar <jayanta.kshirsagar@gmail.com>"]
repository = "https://github.com/kjayanta25/epirust"